apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "opsdroid.fullname" . }}
  labels:
    {{- include "opsdroid.labels" . | nindent 4 }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
{{- end }}
  selector:
    matchLabels:
      {{- include "opsdroid.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/opsdroid-config.yaml") . | sha256sum }}
        {{- toYaml . | nindent 8 }}
    {{- end }}
      labels:
        {{- include "opsdroid.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "opsdroid.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /stats
              port: http
            initialDelaySeconds: 120
            periodSeconds: 10              
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          {{- if $.Values.configuration }}
          - name: config
            mountPath: "/root/.config/opsdroid/configuration.yaml"
            subPath: configuration.yaml
            readOnly: false
          {{- end }} 
          env:
            {{- range .Values.environment }}
            - name: {{ .name }}
              valueFrom:
                secretKeyRef:
                  name: opsdroid-config
                  key: {{ .name }}
            {{- end }}
      volumes:
        {{- if $.Values.configuration }}
        - name: config
          configMap:
            name: opsdroid-config
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
